
let project={id:Date.now().toString(),empresa:{},setores:[],funcoes:[],ghe:[],riscos:[],salvoEm:''};
const $=id=>document.getElementById(id);
const empFields=['razaoSocial','nomeFantasia','cnpj','cnae','grauRisco','numTrabalhadores','endereco','responsavelEmpresa','contatoEmpresa','emailEmpresa','dataElaboracao','atividadeEmpresa','respSst','funcaoRespSst','medicoTrabalho','crmMedico','engSeguranca','creaEng'];

function init(){
 $('dataElaboracao').value=new Date().toISOString().slice(0,10);
 document.querySelectorAll('#menu button').forEach(b=>b.onclick=()=>openView(b.dataset.view,b));
 $('newProjectBtn').onclick=newProject;$('saveProjectBtn').onclick=saveProject;
 $('addSetor').onclick=()=>openEntityModal('setor');$('addFuncao').onclick=()=>openEntityModal('funcao');$('addGhe').onclick=()=>openEntityModal('ghe');$('addRisco').onclick=()=>openEntityModal('risco');
 $('closeModal').onclick=closeModal;$('previewPgr').onclick=previewPgr;$('printPgr').onclick=()=>V8Report.print(collect());$('closeReport').onclick=closeReport;$('printFromPreview').onclick=()=>V8Report.print(window._previewProject||collect());
 $('searchProjects').oninput=renderProjects;$('cnpj').oninput=e=>e.target.value=formatCNPJ(e.target.value);
 renderAll();
}
function openView(v,btn){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$('view-'+v).classList.add('active');document.querySelectorAll('#menu button').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');const names={dashboard:'Dashboard',inspecao:'Checklist de Inspeção SST',empresa:'Empresa',setores:'Setores',funcoes:'Funções',ghe:'GHE',riscos:'Inventário de riscos',plano:'Plano de ação',pgr:'PGR / NR-1',pcmso:'PCMSO',ltcat:'LTCAT',projetos:'Projetos salvos'};$('pageTitle').textContent=names[v]||v;document.body.classList.toggle('inspecao-open',v==='inspecao');if(v==='plano')renderPlano();if(v==='pgr')renderPgrSummary();if(v==='projetos')renderProjects()}
function formatCNPJ(value){const d=String(value||'').replace(/\D/g,'').slice(0,14);if(d.length<=2)return d;if(d.length<=5)return d.slice(0,2)+'.'+d.slice(2);if(d.length<=8)return d.slice(0,2)+'.'+d.slice(2,5)+'.'+d.slice(5);if(d.length<=12)return d.slice(0,2)+'.'+d.slice(2,5)+'.'+d.slice(5,8)+'/'+d.slice(8);return d.slice(0,2)+'.'+d.slice(2,5)+'.'+d.slice(5,8)+'/'+d.slice(8,12)+'-'+d.slice(12)}
function collect(){empFields.forEach(f=>project.empresa[f]=$(f).value);project.salvoEm=new Date().toLocaleString('pt-BR');return JSON.parse(JSON.stringify(project))}
function apply(p){project=JSON.parse(JSON.stringify(p));empFields.forEach(f=>$(f).value=project.empresa?.[f]||'');renderAll();$('projectLabel').textContent=project.empresa?.razaoSocial||'Projeto SST'}
function saveProject(){collect();if(!project.empresa.razaoSocial)return alert('Informe a razão social.');V8Storage.save(project);renderProjects();$('projectLabel').textContent=project.empresa.razaoSocial;alert('Projeto salvo neste aparelho.')}
function newProject(){if(!confirm('Criar um novo projeto? Salve o atual antes, se necessário.'))return;project={id:Date.now().toString(),empresa:{},setores:[],funcoes:[],ghe:[],riscos:[],salvoEm:''};empFields.forEach(f=>$(f).value='');$('dataElaboracao').value=new Date().toISOString().slice(0,10);$('respSst').value='Francson Menezes Alves';$('funcaoRespSst').value='Técnico de Segurança do Trabalho';$('projectLabel').textContent='Novo projeto SST';renderAll()}
function renderAll(){renderSetores();renderFuncoes();renderGhe();renderRiscos();renderPlano();renderDashboard()}
function renderDashboard(){const highs=project.riscos.filter(r=>Number(r.prob)*Number(r.sev)>=10).length;$('mSetores').textContent=project.setores.length;$('mFuncoes').textContent=project.funcoes.length;$('mGhe').textContent=project.ghe.length;$('mRiscos').textContent=project.riscos.length;$('mAltos').textContent=highs;const tasks=[['Empresa',!!project.empresa.razaoSocial],['Setores',project.setores.length>0],['Funções',project.funcoes.length>0],['GHE',project.ghe.length>0],['Inventário',project.riscos.length>0],['Plano de ação',project.riscos.some(r=>r.acao)]];$('progressList').innerHTML=tasks.map(([n,ok])=>`<div class="progress-item"><div><span>${n}</span><b>${ok?'Concluído':'Pendente'}</b></div><div class="bar"><span style="width:${ok?100:15}%"></span></div></div>`).join('')}
function closeModal(){$('modal').classList.add('hidden')}function closeReport(){$('reportModal').classList.add('hidden')}
function options(list,key='nome'){return `<option value="">Selecione...</option>${list.map(x=>`<option>${V8Report.esc(x[key]||'')}</option>`).join('')}`}
function openEntityModal(type,index=null){
 const edit=index!==null;let item=edit?project[type==='setor'?'setores':type==='funcao'?'funcoes':type==='ghe'?'ghe':'riscos'][index]:{};
 const titles={setor:'Setor / ambiente',funcao:'Função',ghe:'GHE',risco:'Risco ocupacional'};$('modalTitle').textContent=(edit?'Editar ':'Novo ')+titles[type];
 let h='';
 if(type==='setor')h=`<div class="form-grid two"><label>Nome<input id="eNome" value="${V8Report.esc(item.nome||'')}"></label><label>Tipo de ambiente<input id="eAmbiente" value="${V8Report.esc(item.ambiente||'')}"></label><label class="span2">Descrição<textarea id="eDescricao">${V8Report.esc(item.descricao||'')}</textarea></label></div>`;
 if(type==='funcao')h=`<div class="form-grid two"><label>Função<input id="eNome" value="${V8Report.esc(item.nome||'')}"></label><label>Setor<select id="eSetor">${options(project.setores)}</select></label><label>Quantidade<input id="eQtd" type="number" min="0" value="${V8Report.esc(item.quantidade||'1')}"></label><label>CBO<input id="eCbo" value="${V8Report.esc(item.cbo||'')}"></label><label class="span2">Atividades<textarea id="eAtividades">${V8Report.esc(item.atividades||'')}</textarea></label></div>`;
 if(type==='ghe')h=`<div class="form-grid two"><label>Identificação do GHE<input id="eNome" value="${V8Report.esc(item.nome||'')}"></label><label>Setor<select id="eSetor">${options(project.setores)}</select></label><label class="span2">Funções incluídas<input id="eFuncoes" value="${V8Report.esc(item.funcoes||'')}" placeholder="Ex.: Porteiro, Zelador"></label><label class="span2">Descrição da exposição / similaridade<textarea id="eDescricao">${V8Report.esc(item.descricao||'')}</textarea></label></div>`;
 if(type==='risco')h=`<div class="form-grid two"><label>GHE<select id="eGhe">${options(project.ghe)}</select></label><label>Função<select id="eFuncao">${options(project.funcoes)}</select></label><label>Grupo<select id="eGrupo"><option>Físico</option><option>Químico</option><option>Biológico</option><option>Ergonômico</option><option>Acidente</option><option>Psicossocial relacionado ao trabalho</option></select></label><label>Perigo / fator de risco<input id="ePerigo" value="${V8Report.esc(item.perigo||'')}"></label><label class="span2">Fonte / circunstância<textarea id="eFonte">${V8Report.esc(item.fonte||'')}</textarea></label><label class="span2">Possíveis lesões / agravos<textarea id="eDano">${V8Report.esc(item.dano||'')}</textarea></label><label class="span2">Controles existentes<textarea id="eControles">${V8Report.esc(item.controles||'')}</textarea></label><label>Probabilidade (1–5)<input id="eProb" type="number" min="1" max="5" value="${item.prob||1}"></label><label>Severidade (1–5)<input id="eSev" type="number" min="1" max="5" value="${item.sev||1}"></label><label class="span2">Medida / ação proposta<textarea id="eAcao">${V8Report.esc(item.acao||'')}</textarea></label><label>Responsável<input id="eResponsavel" value="${V8Report.esc(item.responsavel||'')}"></label><label>Prazo<input id="ePrazo" type="date" value="${item.prazo||''}"></label><label>Status<select id="eStatus"><option>Pendente</option><option>Em andamento</option><option>Concluído</option></select></label></div>`;
 h+=`<div style="margin-top:14px;text-align:right"><button class="primary" id="saveEntity">Salvar</button></div>`;$('modalBody').innerHTML=h;
 if(type==='funcao'&&item.setor)$('eSetor').value=item.setor;if(type==='ghe'&&item.setor)$('eSetor').value=item.setor;
 if(type==='risco'){if(item.ghe)$('eGhe').value=item.ghe;if(item.funcao)$('eFuncao').value=item.funcao;if(item.grupo)$('eGrupo').value=item.grupo;if(item.status)$('eStatus').value=item.status}
 $('saveEntity').onclick=()=>saveEntity(type,index);$('modal').classList.remove('hidden')
}
function saveEntity(type,index){
 let obj;
 if(type==='setor')obj={nome:$('eNome').value,ambiente:$('eAmbiente').value,descricao:$('eDescricao').value};
 if(type==='funcao')obj={nome:$('eNome').value,setor:$('eSetor').value,quantidade:$('eQtd').value,cbo:$('eCbo').value,atividades:$('eAtividades').value};
 if(type==='ghe')obj={nome:$('eNome').value,setor:$('eSetor').value,funcoes:$('eFuncoes').value,descricao:$('eDescricao').value};
 if(type==='risco')obj={ghe:$('eGhe').value,funcao:$('eFuncao').value,grupo:$('eGrupo').value,perigo:$('ePerigo').value,fonte:$('eFonte').value,dano:$('eDano').value,controles:$('eControles').value,prob:$('eProb').value,sev:$('eSev').value,acao:$('eAcao').value,responsavel:$('eResponsavel').value,prazo:$('ePrazo').value,status:$('eStatus').value};
 const arr=project[type==='setor'?'setores':type==='funcao'?'funcoes':type==='ghe'?'ghe':'riscos'];if(index===null)arr.push(obj);else arr[index]=obj;closeModal();renderAll()
}
function entityList(root,arr,type,details){root.innerHTML=arr.length?'':'<div class="notice">Nenhum registro cadastrado.</div>';arr.forEach((x,i)=>{const d=document.createElement('div');d.className='entity-card';d.innerHTML=`<div class="entity-head"><div><div class="entity-title">${V8Report.esc(x.nome||x.perigo||'Registro')}</div><div class="entity-meta">${details(x)}</div></div><div class="entity-actions"><button class="outline">Editar</button><button class="danger">Excluir</button></div></div>`;const bs=d.querySelectorAll('button');bs[0].onclick=()=>openEntityModal(type,i);bs[1].onclick=()=>{if(confirm('Excluir este registro?')){arr.splice(i,1);renderAll()}};root.appendChild(d)})}
function renderSetores(){entityList($('setoresList'),project.setores,'setor',x=>`${V8Report.esc(x.ambiente||'')} · ${V8Report.esc(x.descricao||'')}`)}
function renderFuncoes(){entityList($('funcoesList'),project.funcoes,'funcao',x=>`${V8Report.esc(x.setor||'')} · ${V8Report.esc(x.quantidade||'0')} trabalhador(es) · ${V8Report.esc(x.cbo||'')}`)}
function renderGhe(){entityList($('gheList'),project.ghe,'ghe',x=>`${V8Report.esc(x.setor||'')} · ${V8Report.esc(x.funcoes||'')}`)}
function renderRiscos(){const root=$('riscosList');root.innerHTML=project.riscos.length?'':'<div class="notice">Nenhum risco cadastrado.</div>';project.riscos.forEach((r,i)=>{const score=Number(r.prob)*Number(r.sev),lvl=V8Report.level(score),cl=lvl==='Baixo'?'baixo':lvl==='Moderado'?'moderado':lvl==='Alto'?'alto':'critico';const d=document.createElement('div');d.className='risk-row';d.innerHTML=`<div><b>${V8Report.esc(r.perigo)}</b><br><span>${V8Report.esc(r.ghe||r.funcao||'-')}</span></div><div>${V8Report.esc(r.grupo)}</div><div>P ${r.prob} × S ${r.sev}</div><div class="risk-level ${cl}">${lvl}</div><div>${V8Report.esc(r.status||'Pendente')}</div><div class="entity-actions"><button class="outline">Editar</button><button class="danger">Excluir</button></div>`;const bs=d.querySelectorAll('button');bs[0].onclick=()=>openEntityModal('risco',i);bs[1].onclick=()=>{if(confirm('Excluir este risco?')){project.riscos.splice(i,1);renderAll()}};root.appendChild(d)})}
function renderPlano(){const rows=project.riscos.filter(r=>r.acao);$('planoTable').innerHTML=rows.length?`<table class="table"><thead><tr><th>Risco</th><th>Nível</th><th>Ação</th><th>Responsável</th><th>Prazo</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${V8Report.esc(r.perigo)}</td><td>${V8Report.level(Number(r.prob)*Number(r.sev))}</td><td>${V8Report.esc(r.acao)}</td><td>${V8Report.esc(r.responsavel||'-')}</td><td>${V8Report.fmt(r.prazo)}</td><td>${V8Report.esc(r.status||'Pendente')}</td></tr>`).join('')}</tbody></table>`:'<div class="notice">Cadastre ações nos riscos do inventário para formar o plano de ação.</div>'}
function renderPgrSummary(){const p=collect(),high=p.riscos.filter(r=>Number(r.prob)*Number(r.sev)>=10).length;$('pgrSummary').innerHTML=`<div class="cards metrics" style="grid-template-columns:repeat(4,1fr)"><article><b>${p.setores.length}</b><span>Setores</span></article><article><b>${p.ghe.length}</b><span>GHEs</span></article><article><b>${p.riscos.length}</b><span>Riscos</span></article><article><b>${high}</b><span>Altos/críticos</span></article></div>`}
function previewPgr(){const p=collect();if(!p.empresa.razaoSocial)return alert('Preencha os dados da empresa.');window._previewProject=p;$('reportPreview').innerHTML=V8Report.build(p);$('reportModal').classList.remove('hidden')}
function renderProjects(){const q=($('searchProjects').value||'').toLowerCase(),root=$('projectsList'),list=V8Storage.list().filter(p=>(p.empresa?.razaoSocial||'').toLowerCase().includes(q));root.innerHTML=list.length?'':'<div class="notice">Nenhum projeto salvo.</div>';list.forEach(p=>{const d=document.createElement('div');d.className='entity-card';d.innerHTML=`<div class="entity-head"><div><div class="entity-title">${V8Report.esc(p.empresa?.razaoSocial||'Sem nome')}</div><div class="entity-meta">${V8Report.esc(p.empresa?.cnpj||'')} · ${p.riscos?.length||0} risco(s) · salvo ${V8Report.esc(p.salvoEm||'')}</div></div><div class="entity-actions"><button class="primary">Abrir</button><button class="dark">PGR</button><button class="danger">Excluir</button></div></div>`;const bs=d.querySelectorAll('button');bs[0].onclick=()=>{apply(p);openView('dashboard',document.querySelector('[data-view="dashboard"]'))};bs[1].onclick=()=>V8Report.print(p);bs[2].onclick=()=>{if(confirm('Excluir este projeto?')){V8Storage.remove(p.id);renderProjects()}};root.appendChild(d)})}
document.addEventListener('DOMContentLoaded',init);
