
const V8Report=(()=>{
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
 const fmt=d=>{if(!d)return'-';const p=String(d).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:d};
 const logo='assets/logo.jpeg';
 function head(n,total){return `<div class="pgr-head"><img src="${logo}"><b>PROGRAMA DE GERENCIAMENTO DE RISCOS<br>NR-1 / GRO</b></div><div class="pgr-foot"><span>(61) 98515-0519 · futurofacilitetreinamentos@gmail.com</span><span>Página ${n} de ${total}</span></div>`}
 function page(content,n,total){return `<section class="pgr-page">${head(n,total)}<div class="pgr-content">${content}</div></section>`}
 function level(score){return score<=4?'Baixo':score<=9?'Moderado':score<=16?'Alto':'Crítico'}
 function drpsBlock(p){
  const d=p.drps||{n:0,topicos:[],altos:[],porSetor:{}};
  const topics=(d.topicos&&d.topicos.length)?d.topicos:(typeof DRPSData!=='undefined'?DRPSData.TOPICS.map(t=>({id:t.id,nome:t.nome,media:0,gravidade:'—',gravidadeN:0,fonte:DRPSData.FONTES[t.id]||'',agravo:DRPSData.AGRAVOS})):[]);
  const nResp=d.n||0;
  const setores=Object.entries(d.porSetor||{}).map(([k,v])=>`${esc(k)} (${v})`).join('; ')||'—';
  const intro=nResp
   ? `Esta seção atende à NR-1 quanto à identificação, avaliação e informação dos riscos psicossociais relacionados ao trabalho. O Diagnóstico de Riscos Psicossociais (DRPS) foi aplicado de forma confidencial (50 questões, 13 tópicos). Os resultados entram neste PGR apenas de forma coletiva, sem identificação nominal dos trabalhadores.`
   : `A NR-1 exige que os riscos psicossociais relacionados ao trabalho sejam identificados, avaliados e informados neste PGR. O Diagnóstico de Riscos Psicossociais (DRPS) ainda não foi aplicado neste condomínio. Esta seção permanece aberta até a coleta das respostas dos trabalhadores.`;
  const rows=topics.map(t=>{
   const media=nResp && t.media?Number(t.media).toFixed(2):'—';
   const g=nResp?esc(t.gravidade||'—'):'A avaliar';
   const cls=t.gravidadeN>=3?' class="alta"':'';
   return `<tr${cls}><td>${esc(t.nome)}</td><td>${media}</td><td>${g}</td></tr>`;
  }).join('')||'<tr><td colspan="3">Tópicos do DRPS indisponíveis.</td></tr>';
  const fontes=topics.map(t=>{
   const cls=t.gravidadeN>=3?' class="alta"':'';
   return `<tr${cls}><td>${esc(t.nome)}</td><td>${esc(t.gravidade||'—')}</td><td>${esc(t.fonte||'')}</td></tr>`;
  }).join('');
  const page1=`<h1 class="pgr-title">5. Riscos psicossociais (DRPS / NR-1)</h1><div class="pgr-text">${intro}</div><div class="pgr-kpi"><span><b>${nResp}</b> resposta(s) coletiva(s)</span><span><b>${(d.altos||[]).length}</b> tópico(s) em gravidade alta</span><span>Setores: ${setores}</span></div><h2 class="pgr-sub">Inventário coletivo por tópico</h2><table class="pgr-table compact"><thead><tr><th>Tópico / fator psicossocial</th><th>Média (1–5)</th><th>Gravidade</th></tr></thead><tbody>${rows}</tbody></table><div class="pgr-text" style="margin-top:3mm">Escala: 1 Nunca · 2 Raramente · 3 Às vezes · 4 Frequentemente · 5 Sempre. Gravidade: média arredondada ≥ 4 Alta; = 3 Média; ≤ 2 Baixa.</div>`;
  const page2=`<h1 class="pgr-title">5. Riscos psicossociais — fontes e agravos</h1><h2 class="pgr-sub">Fonte geradora por tópico</h2><table class="pgr-table compact"><thead><tr><th>Tópico</th><th>Gravidade</th><th>Fonte geradora (circunstâncias)</th></tr></thead><tbody>${fontes}</tbody></table><div class="pgr-text" style="margin-top:3mm"><b>Possíveis agravos:</b> ${esc(topics[0]?.agravo||'transtornos psicológicos e emocionais, burnout, ansiedade, insônia, medo, desmotivação e demais agravos à saúde mental.')}</div><h2 class="pgr-sub">Medidas organizacionais</h2><div class="pgr-text">Os fatores em gravidade alta devem ser tratados no plano de ação deste PGR (item 6), com medidas organizacionais e relacionais — canal de denúncia, suporte da liderança, clareza de papel, dimensionamento de equipe, comunicação e reconhecimento — sem exposição nominal dos trabalhadores. Reaplicar o DRPS após as intervenções ou quando houver mudança relevante na organização do trabalho.</div><div class="pgr-text">Confidencialidade: as respostas individuais não constam deste documento. O PGR informa apenas o resultado coletivo, por tópico.</div>`;
  return nResp?[page1,page2]:[page1];
 }
 function build(p){
  const risks=p.riscos||[], actions=risks.filter(r=>r.acao);
  const riskChunks=[];for(let i=0;i<risks.length;i+=10)riskChunks.push(risks.slice(i,i+10));if(!riskChunks.length)riskChunks.push([]);
  const actionChunks=[];for(let i=0;i<actions.length;i+=10)actionChunks.push(actions.slice(i,i+10));if(!actionChunks.length)actionChunks.push([]);
  const drpsPages=drpsBlock(p);
  const middleCount=3+riskChunks.length+drpsPages.length+actionChunks.length;
  const total=middleCount+2;let n=1,html='';
  html+=`<section class="pgr-page pgr-cover"><div class="pgr-cover-main"><img src="${logo}"><h1>PROGRAMA DE GERENCIAMENTO<br>DE RISCOS</h1><h2>NR-1 · GRO · PGR</h2></div><div class="pgr-cover-info"><div><b>Organização</b><span>${esc(p.empresa.razaoSocial||'-')}</span></div><div><b>CNPJ</b><span>${esc(p.empresa.cnpj||'-')}</span></div><div><b>Nome fantasia</b><span>${esc(p.empresa.nomeFantasia||'-')}</span></div><div><b>Data</b><span>${fmt(p.empresa.dataElaboracao)}</span></div><div style="grid-column:1/-1"><b>Endereço</b><span>${esc(p.empresa.endereco||'-')}</span></div></div><div class="pgr-cover-band"><span>Futuro Facilite Treinamentos</span><span>Gestão de Segurança e Saúde no Trabalho</span></div></section>`;n++;
  html+=page(`<h1 class="pgr-title">1. Identificação e caracterização da organização</h1><table class="pgr-table"><tr><th>Razão social</th><td>${esc(p.empresa.razaoSocial||'-')}</td><th>CNPJ</th><td>${esc(p.empresa.cnpj||'-')}</td></tr><tr><th>CNAE</th><td>${esc(p.empresa.cnae||'-')}</td><th>Grau de risco</th><td>${esc(p.empresa.grauRisco||'-')}</td></tr><tr><th>Trabalhadores</th><td>${esc(p.empresa.numTrabalhadores||'0')}</td><th>Responsável</th><td>${esc(p.empresa.responsavelEmpresa||'-')}</td></tr><tr><th>Endereço</th><td colspan="3">${esc(p.empresa.endereco||'-')}</td></tr></table><h2 class="pgr-sub">Atividades da organização</h2><div class="pgr-text">${esc(p.empresa.atividadeEmpresa||'-')}</div><h2 class="pgr-sub">Responsáveis técnicos cadastrados</h2><table class="pgr-table"><tr><th>SST</th><td>${esc(p.empresa.respSst||'-')}${p.empresa.regSst?' · Registro '+esc(p.empresa.regSst):''}</td></tr><tr><th>Médico do Trabalho</th><td>${esc(p.empresa.medicoTrabalho||'-')} ${p.empresa.crmMedico?' · '+esc(p.empresa.crmMedico):''}</td></tr><tr><th>Engenharia de Segurança</th><td>${esc(p.empresa.engSeguranca||'-')} ${p.empresa.creaEng?' · '+esc(p.empresa.creaEng):''}</td></tr></table>`,n++,total);
  html+=page(`<h1 class="pgr-title">2. Estrutura organizacional e grupos de exposição</h1><h2 class="pgr-sub">Setores</h2><table class="pgr-table"><thead><tr><th>Setor</th><th>Descrição</th><th>Ambiente</th></tr></thead><tbody>${(p.setores||[]).map(s=>`<tr><td>${esc(s.nome)}</td><td>${esc(s.descricao)}</td><td>${esc(s.ambiente)}</td></tr>`).join('')||'<tr><td colspan="3">Nenhum setor cadastrado.</td></tr>'}</tbody></table><h2 class="pgr-sub">Funções</h2><table class="pgr-table"><thead><tr><th>Função</th><th>Setor</th><th>Qtd.</th><th>Atividades</th></tr></thead><tbody>${(p.funcoes||[]).map(f=>`<tr><td>${esc(f.nome)}</td><td>${esc(f.setor)}</td><td>${esc(f.quantidade)}</td><td>${esc(f.atividades)}</td></tr>`).join('')||'<tr><td colspan="4">Nenhuma função cadastrada.</td></tr>'}</tbody></table><h2 class="pgr-sub">GHE</h2><table class="pgr-table"><thead><tr><th>GHE</th><th>Setor</th><th>Funções</th><th>Descrição</th></tr></thead><tbody>${(p.ghe||[]).map(g=>`<tr><td>${esc(g.nome)}</td><td>${esc(g.setor)}</td><td>${esc(g.funcoes)}</td><td>${esc(g.descricao)}</td></tr>`).join('')||'<tr><td colspan="4">Nenhum GHE cadastrado.</td></tr>'}</tbody></table>`,n++,total);
  html+=page(`<h1 class="pgr-title">3. Critérios de avaliação e classificação</h1><div class="pgr-text">Para priorização interna das ações preventivas, esta versão utiliza matriz 5 × 5 baseada na multiplicação entre Probabilidade (1 a 5) e Severidade (1 a 5). O resultado orienta a priorização e deve ser validado pela equipe responsável pelo GRO, considerando os critérios técnicos aplicáveis à organização. Os riscos psicossociais relacionados ao trabalho são avaliados pelo DRPS (escala 1 a 5) e informados no item 5 deste PGR.</div><h2 class="pgr-sub">Faixas internas</h2><div class="matrix"><div class="low">1–4<br>Baixo</div><div class="med">5–9<br>Moderado</div><div class="high">10–16<br>Alto</div><div class="crit">17–25<br>Crítico</div></div><h2 class="pgr-sub">Hierarquia de controles</h2><div class="pgr-text">As medidas propostas devem priorizar eliminação do perigo e redução dos riscos por medidas de prevenção, observando controles coletivos, administrativos/organizacionais e, quando cabível, equipamentos de proteção individual.</div>`,n++,total);
  riskChunks.forEach((ch,ix)=>{html+=page(`<h1 class="pgr-title">4. Inventário de riscos ${riskChunks.length>1?`(${ix+1}/${riskChunks.length})`:''}</h1><table class="pgr-table"><thead><tr><th>GHE / função</th><th>Grupo</th><th>Perigo / fator</th><th>Dano</th><th>P</th><th>S</th><th>Nível</th><th>Controles existentes</th></tr></thead><tbody>${ch.map(r=>`<tr><td>${esc(r.ghe||r.funcao||'-')}</td><td>${esc(r.grupo)}</td><td>${esc(r.perigo)}</td><td>${esc(r.dano)}</td><td>${esc(r.prob)}</td><td>${esc(r.sev)}</td><td>${level(Number(r.prob)*Number(r.sev))}</td><td>${esc(r.controles)}</td></tr>`).join('')||'<tr><td colspan="8">Nenhum risco cadastrado.</td></tr>'}</tbody></table>${ix===riskChunks.length-1?`<div class="pgr-text" style="margin-top:3mm">Os riscos psicossociais relacionados ao trabalho, exigidos pela NR-1, estão informados no item 5 deste PGR, com base no resultado coletivo do DRPS.</div>`:''}`,n++,total)});
  drpsPages.forEach(content=>{html+=page(content,n++,total)});
  actionChunks.forEach((ch,ix)=>{html+=page(`<h1 class="pgr-title">6. Plano de ação ${actionChunks.length>1?`(${ix+1}/${actionChunks.length})`:''}</h1>${ix===0?`<div class="pgr-text">Inclui as medidas cadastradas para os riscos ocupacionais e, quando o DRPS indicar gravidade alta, as intervenções organizacionais correspondentes aos fatores psicossociais do item 5.</div>`:''}<table class="pgr-table"><thead><tr><th>Risco</th><th>Nível</th><th>Medida proposta</th><th>Responsável</th><th>Prazo</th><th>Status</th></tr></thead><tbody>${ch.map(r=>`<tr><td>${esc(r.perigo)}</td><td>${level(Number(r.prob)*Number(r.sev))}</td><td>${esc(r.acao)}</td><td>${esc(r.responsavel)}</td><td>${fmt(r.prazo)}</td><td>${esc(r.status||'Pendente')}</td></tr>`).join('')||'<tr><td colspan="6">Nenhuma ação cadastrada.</td></tr>'}</tbody></table>`,n++,total)});
  html+=page(`<h1 class="pgr-title">7. Conclusão e responsabilidades</h1><div class="pgr-text">Este documento consolida as informações cadastradas no sistema para o gerenciamento dos riscos ocupacionais da organização, incluindo os riscos psicossociais relacionados ao trabalho informados no item 5 (DRPS / NR-1). O inventário de riscos, o resultado coletivo do DRPS e o plano de ação devem permanecer atualizados conforme mudanças nos processos, ambientes, atividades, organização do trabalho, controles e demais situações que alterem a exposição dos trabalhadores.</div><div class="sign-grid"><div class="sign">${esc(p.empresa.respSst||'Responsável SST')}<br>${p.empresa.regSst?esc('Registro '+p.empresa.regSst):esc(p.empresa.funcaoRespSst||'Técnico de Segurança do Trabalho')}</div><div class="sign">${esc(p.empresa.responsavelEmpresa||'Responsável pela organização')}<br>Representante da organização</div></div>`,n++,total);
  return `<div class="pgr-doc">${html}</div>`
 }
 function pcmsoHead(n,total){return `<div class="pgr-head"><img src="${logo}"><b>PROGRAMA DE CONTROLE MÉDICO<br>DE SAÚDE OCUPACIONAL · NR-7</b></div><div class="pgr-foot"><span>(61) 98515-0519 · futurofacilitetreinamentos@gmail.com</span><span>Página ${n} de ${total}</span></div>`}
 function pcmsoPage(content,n,total){return `<section class="pgr-page">${pcmsoHead(n,total)}<div class="pgr-content">${content}</div></section>`}
 function buildPcmso(p){
  const plan=typeof PCMSOData!=='undefined'?PCMSOData.plan(p):{medico:{},byFunc:[],riscos:[],nExames:0};
  const examRows=[];
  (plan.byFunc||[]).forEach(f=>f.exames.forEach(e=>examRows.push({funcao:f.funcao,qtd:f.qtd,...e})));
  const examChunks=[];for(let i=0;i<examRows.length;i+=12)examChunks.push(examRows.slice(i,i+12));if(!examChunks.length)examChunks.push([]);
  const riskRows=(p.riscos||[]).map(r=>({funcao:r.funcao||r.ghe||'-',grupo:r.grupo,perigo:r.perigo,dano:r.dano}));
  const riskChunks=[];for(let i=0;i<riskRows.length;i+=12)riskChunks.push(riskRows.slice(i,i+12));if(!riskChunks.length)riskChunks.push([]);
  const total=4+riskChunks.length+examChunks.length;let n=1,html='';
  const med=plan.medico||{};
  html+=`<section class="pgr-page pgr-cover"><div class="pgr-cover-main"><img src="${logo}"><h1>PROGRAMA DE CONTROLE MÉDICO<br>DE SAÚDE OCUPACIONAL</h1><h2>NR-7 · PCMSO</h2></div><div class="pgr-cover-info"><div><b>Organização</b><span>${esc(p.empresa.razaoSocial||'-')}</span></div><div><b>CNPJ</b><span>${esc(p.empresa.cnpj||'-')}</span></div><div><b>Médico responsável</b><span>${esc(med.nome||'-')}</span></div><div><b>CRM</b><span>${esc(med.crm||'-')}</span></div><div><b>Data</b><span>${fmt(p.empresa.dataElaboracao)}</span></div><div style="grid-column:1/-1"><b>Endereço</b><span>${esc(p.empresa.endereco||'-')}</span></div></div><div class="pgr-cover-band"><span>Futuro Facilite Treinamentos</span><span>Gestão de Segurança e Saúde no Trabalho</span></div></section>`;n++;
  html+=pcmsoPage(`<h1 class="pgr-title">1. Identificação e responsabilidade médica</h1><table class="pgr-table"><tr><th>Razão social</th><td>${esc(p.empresa.razaoSocial||'-')}</td><th>CNPJ</th><td>${esc(p.empresa.cnpj||'-')}</td></tr><tr><th>Trabalhadores</th><td>${esc(p.empresa.numTrabalhadores||'0')}</td><th>Grau de risco</th><td>${esc(p.empresa.grauRisco||'-')}</td></tr><tr><th>Endereço</th><td colspan="3">${esc(p.empresa.endereco||'-')}</td></tr></table><h2 class="pgr-sub">Médico coordenador do PCMSO</h2><table class="pgr-table"><tr><th>Nome</th><td>${esc(med.nome||'Médico não selecionado no cadastro do condomínio')}</td></tr><tr><th>CRM</th><td>${esc(med.crm||'-')}</td></tr></table><div class="pgr-text">Este PCMSO é elaborado com base no inventário de riscos do PGR (NR-1) deste condomínio. Os exames e periodicidades abaixo são proposta técnica para revisão e aprovação do Médico do Trabalho, nos termos da NR-7.</div>`,n++,total);
  html+=pcmsoPage(`<h1 class="pgr-title">2. Objetivos e diretrizes</h1><div class="pgr-text">O PCMSO tem por objetivo promover e preservar a saúde do conjunto dos trabalhadores, rastrear precocemente agravos relacionados ao trabalho e subsidiar as ações de prevenção do GRO/PGR. Os exames ocupacionais previstos são: admissional (A), periódico (P), de retorno ao trabalho (R), de mudança de função (M) e demissional (D).</div><h2 class="pgr-sub">Integração com o PGR</h2><div class="pgr-text">Os fatores de risco ocupacionais, inclusive psicossociais quando identificados no DRPS, são importados do PGR vigente. Alterações no inventário de riscos exigem revisão deste PCMSO pelo médico coordenador.</div><h2 class="pgr-sub">ASO</h2><div class="pgr-text">Para cada exame realizado será emitido o Atestado de Saúde Ocupacional (ASO) em duas vias, com indicação de aptidão para a função, exames complementares realizados e data do próximo exame, conforme NR-7. O ASO individual não substitui este programa.</div>`,n++,total);
  riskChunks.forEach((ch,ix)=>{html+=pcmsoPage(`<h1 class="pgr-title">3. Riscos ocupacionais importados do PGR ${riskChunks.length>1?`(${ix+1}/${riskChunks.length})`:''}</h1><table class="pgr-table compact"><thead><tr><th>Função / GHE</th><th>Grupo</th><th>Perigo / fator</th><th>Possíveis agravos</th></tr></thead><tbody>${ch.map(r=>`<tr><td>${esc(r.funcao)}</td><td>${esc(r.grupo||'-')}</td><td>${esc(r.perigo||'-')}</td><td>${esc(r.dano||'-')}</td></tr>`).join('')||'<tr><td colspan="4">Nenhum risco cadastrado no PGR. Complete o inventário para fechar o quadro de exames.</td></tr>'}</tbody></table>`,n++,total)});
  examChunks.forEach((ch,ix)=>{html+=pcmsoPage(`<h1 class="pgr-title">4. Quadro de exames ocupacionais ${examChunks.length>1?`(${ix+1}/${examChunks.length})`:''}</h1><table class="pgr-table compact"><thead><tr><th>Função</th><th>Qtd.</th><th>Exame</th><th>Tipos</th><th>Periodicidade</th><th>Indicador</th></tr></thead><tbody>${ch.map(e=>`<tr><td>${esc(e.funcao)}</td><td>${esc(e.qtd||'-')}</td><td>${esc(e.exame)}</td><td>${esc(e.tipos)}</td><td>${esc(e.periodo)}</td><td>${esc(e.motivo)}</td></tr>`).join('')||'<tr><td colspan="6">Sem quadro de exames.</td></tr>'}</tbody></table>${ix===examChunks.length-1?`<div class="pgr-text" style="margin-top:3mm">A = admissional · P = periódico · R = retorno ao trabalho · M = mudança de função · D = demissional. Exames complementares podem ser ampliados pelo médico coordenador conforme avaliação clínica e evolução dos riscos.</div>`:''}`,n++,total)});
  html+=pcmsoPage(`<h1 class="pgr-title">5. Conclusão e aprovação</h1><div class="pgr-text">Este PCMSO permanece vinculado ao PGR do condomínio e deve ser reavaliado anualmente ou sempre que houver mudança nos processos, funções, número de trabalhadores ou no perfil de riscos. A execução dos exames, a emissão dos ASOs e o relatório analítico anual ficam sob responsabilidade do médico coordenador.</div><div class="sign-grid"><div class="sign">${esc(med.nome||'Médico do Trabalho')}<br>CRM ${esc(med.crm||'—')}<br>Coordenador do PCMSO</div><div class="sign">${esc(p.empresa.responsavelEmpresa||'Responsável pela organização')}<br>Representante do condomínio</div></div>`,n++,total);
  return `<div class="pgr-doc">${html}</div>`
 }
 function printDoc(html){let h=document.getElementById('printHost');if(!h){h=document.createElement('div');h.id='printHost';document.body.appendChild(h)}h.className='report-preview';h.innerHTML=html;const imgs=[...h.querySelectorAll('img')];let left=imgs.length;const go=()=>setTimeout(()=>window.print(),150);if(!left)return go();const done=()=>{left--;if(left<=0)go()};imgs.forEach(i=>i.complete?done():(i.onload=done,i.onerror=done));setTimeout(go,1800)}
 function print(p){printDoc(build(p))}
 function printPcmso(p){printDoc(buildPcmso(p))}
 function ltcatHead(n,total){return `<div class="pgr-head"><img src="${logo}"><b>LAUDO TÉCNICO DAS CONDIÇÕES<br>AMBIENTAIS DO TRABALHO · LTCAT</b></div><div class="pgr-foot"><span>(61) 98515-0519 · futurofacilitetreinamentos@gmail.com</span><span>Página ${n} de ${total}</span></div>`}
 function ltcatPage(content,n,total){return `<section class="pgr-page">${ltcatHead(n,total)}<div class="pgr-content">${content}</div></section>`}
 function buildLtcat(p){
  const plan=typeof LTCATData!=='undefined'?LTCATData.plan(p):{eng:{},agentes:[],ocupacionais:[],conclusao:''};
  const ag=plan.agentes||[];
  const agChunks=[];for(let i=0;i<ag.length;i+=6)agChunks.push(ag.slice(i,i+6));if(!agChunks.length)agChunks.push([]);
  const ghe=(p.ghe||[]).length?(p.ghe||[]):[{nome:'Ambientes do condomínio',setor:'-',funcoes:(p.funcoes||[]).map(f=>f.nome).join(', ')||'-',descricao:p.empresa?.atividadeEmpresa||'-'}];
  const total=4+agChunks.length;let n=1,html='';
  const eng=plan.eng||{};
  html+=`<section class="pgr-page pgr-cover"><div class="pgr-cover-main"><img src="${logo}"><h1>LAUDO TÉCNICO DAS CONDIÇÕES<br>AMBIENTAIS DO TRABALHO</h1><h2>LTCAT · Previdenciário</h2></div><div class="pgr-cover-info"><div><b>Organização</b><span>${esc(p.empresa.razaoSocial||'-')}</span></div><div><b>CNPJ</b><span>${esc(p.empresa.cnpj||'-')}</span></div><div><b>Engenharia de Segurança</b><span>${esc(eng.nome||'-')}</span></div><div><b>CREA</b><span>${esc(eng.crea||'-')}</span></div><div><b>Data</b><span>${fmt(p.empresa.dataElaboracao)}</span></div><div style="grid-column:1/-1"><b>Endereço</b><span>${esc(p.empresa.endereco||'-')}</span></div></div><div class="pgr-cover-band"><span>Futuro Facilite Treinamentos</span><span>Gestão de Segurança e Saúde no Trabalho</span></div></section>`;n++;
  html+=ltcatPage(`<h1 class="pgr-title">1. Identificação e objeto</h1><table class="pgr-table"><tr><th>Razão social</th><td>${esc(p.empresa.razaoSocial||'-')}</td><th>CNPJ</th><td>${esc(p.empresa.cnpj||'-')}</td></tr><tr><th>CNAE</th><td>${esc(p.empresa.cnae||'-')}</td><th>Trabalhadores</th><td>${esc(p.empresa.numTrabalhadores||'0')}</td></tr><tr><th>Endereço</th><td colspan="3">${esc(p.empresa.endereco||'-')}</td></tr></table><h2 class="pgr-sub">Profissional legalmente habilitado</h2><table class="pgr-table"><tr><th>Engenharia de Segurança</th><td>${esc(eng.nome||'Engenheiro não selecionado no cadastro')}</td></tr><tr><th>CREA</th><td>${esc(eng.crea||'-')}</td></tr><tr><th>SST de apoio</th><td>${esc(plan.sst?.nome||'-')}${plan.sst?.reg?' · Registro '+esc(plan.sst.reg):''}</td></tr></table><div class="pgr-text">Este LTCAT descreve as condições ambientais do trabalho para fins previdenciários (PPP / aposentadoria especial), com base no inventário de riscos do PGR. Não substitui o PGR nem o PCMSO.</div>`,n++,total);
  html+=ltcatPage(`<h1 class="pgr-title">2. Metodologia</h1><div class="pgr-text">A análise parte da caracterização da organização, setores, funções e GHE cadastrados, e dos perigos/fatores do inventário de riscos. Neste módulo a avaliação dos agentes é qualitativa, observando NR-15, NHO da FUNDACENTRO e o Anexo IV do Decreto 3.048/99. Medições quantitativas, quando existirem, devem ser anexadas e indicadas nos controles do risco.</div><h2 class="pgr-sub">Ambientes e grupos de exposição</h2><table class="pgr-table compact"><thead><tr><th>GHE / ambiente</th><th>Setor</th><th>Funções</th><th>Descrição</th></tr></thead><tbody>${ghe.map(g=>`<tr><td>${esc(g.nome)}</td><td>${esc(g.setor||'-')}</td><td>${esc(g.funcoes||'-')}</td><td>${esc(g.descricao||'-')}</td></tr>`).join('')}</tbody></table>`,n++,total);
  agChunks.forEach((ch,ix)=>{html+=ltcatPage(`<h1 class="pgr-title">3. Agentes e exposição ${agChunks.length>1?`(${ix+1}/${agChunks.length})`:''}</h1><table class="pgr-table compact"><thead><tr><th>GHE / função</th><th>Agente</th><th>Fonte</th><th>EPC / EPI / controles</th></tr></thead><tbody>${ch.map(a=>`<tr><td>${esc(a.ghe)}</td><td>${esc(a.agente)} (${esc(a.grupo)})</td><td>${esc(a.fonte)}</td><td>${esc(a.controles)}</td></tr>`).join('')||'<tr><td colspan="4">Nenhum agente físico, químico ou biológico destacado no inventário. Riscos ergonômicos, de acidente e psicossociais permanecem no PGR, sem enquadramento no Anexo IV.</td></tr>'}</tbody></table>${ch.length?`<h2 class="pgr-sub">Caracterização previdenciária</h2><table class="pgr-table compact"><thead><tr><th>Agente</th><th>Método</th><th>Exposição / enquadramento</th></tr></thead><tbody>${ch.map(a=>`<tr><td>${esc(a.agente)}</td><td>${esc(a.metodo)}</td><td>${esc(a.exposicao)} ${esc(a.enquadramento)}</td></tr>`).join('')}</tbody></table>`:''}`,n++,total)});
  html+=ltcatPage(`<h1 class="pgr-title">4. Conclusão técnica</h1><div class="pgr-text">${esc(plan.conclusao)}</div><div class="pgr-text">Este laudo deve ser atualizado quando houver mudança de processo, ambiente, função, controles ou resultados de avaliações quantitativas. Serve de fundamento para o PPP e não dispensa o gerenciamento dos riscos ocupacionais no PGR.</div><div class="sign-grid"><div class="sign">${esc(eng.nome||'Engenheiro de Segurança do Trabalho')}<br>CREA ${esc(eng.crea||'—')}<br>Responsável técnico pelo LTCAT</div><div class="sign">${esc(p.empresa.responsavelEmpresa||'Responsável pela organização')}<br>Representante do condomínio</div></div>`,n++,total);
  return `<div class="pgr-doc">${html}</div>`
 }
 function printLtcat(p){printDoc(buildLtcat(p))}
 return{build,print,buildPcmso,printPcmso,buildLtcat,printLtcat,level,esc,fmt}
})();
