
const V8Report=(()=>{
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
 const fmt=d=>{if(!d)return'-';const p=String(d).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:d};
 const logo='assets/logo.jpeg';
 function head(n,total){return `<div class="pgr-head"><img src="${logo}"><b>PROGRAMA DE GERENCIAMENTO DE RISCOS<br>NR-1 / GRO</b></div><div class="pgr-foot"><span>(61) 98515-0519 · futurofacilitetreinamentos@gmail.com</span><span>Página ${n} de ${total}</span></div>`}
 function page(content,n,total){return `<section class="pgr-page">${head(n,total)}<div class="pgr-content">${content}</div></section>`}
 function level(score){return score<=4?'Baixo':score<=9?'Moderado':score<=16?'Alto':'Crítico'}
 function build(p){
  const risks=p.riscos||[], actions=risks.filter(r=>r.acao);
  const riskChunks=[];for(let i=0;i<risks.length;i+=10)riskChunks.push(risks.slice(i,i+10));if(!riskChunks.length)riskChunks.push([]);
  const actionChunks=[];for(let i=0;i<actions.length;i+=10)actionChunks.push(actions.slice(i,i+10));if(!actionChunks.length)actionChunks.push([]);
  const middleCount=3+riskChunks.length+actionChunks.length;
  const total=middleCount+2;let n=1,html='';
  html+=`<section class="pgr-page pgr-cover"><div class="pgr-cover-main"><img src="${logo}"><h1>PROGRAMA DE GERENCIAMENTO<br>DE RISCOS</h1><h2>NR-1 · GRO · PGR</h2></div><div class="pgr-cover-info"><div><b>Organização</b><span>${esc(p.empresa.razaoSocial||'-')}</span></div><div><b>CNPJ</b><span>${esc(p.empresa.cnpj||'-')}</span></div><div><b>Nome fantasia</b><span>${esc(p.empresa.nomeFantasia||'-')}</span></div><div><b>Data</b><span>${fmt(p.empresa.dataElaboracao)}</span></div><div style="grid-column:1/-1"><b>Endereço</b><span>${esc(p.empresa.endereco||'-')}</span></div></div><div class="pgr-cover-band"><span>Futuro Facilite Treinamentos</span><span>Gestão de Segurança e Saúde no Trabalho</span></div></section>`;n++;
  html+=page(`<h1 class="pgr-title">1. Identificação e caracterização da organização</h1><table class="pgr-table"><tr><th>Razão social</th><td>${esc(p.empresa.razaoSocial||'-')}</td><th>CNPJ</th><td>${esc(p.empresa.cnpj||'-')}</td></tr><tr><th>CNAE</th><td>${esc(p.empresa.cnae||'-')}</td><th>Grau de risco</th><td>${esc(p.empresa.grauRisco||'-')}</td></tr><tr><th>Trabalhadores</th><td>${esc(p.empresa.numTrabalhadores||'0')}</td><th>Responsável</th><td>${esc(p.empresa.responsavelEmpresa||'-')}</td></tr><tr><th>Endereço</th><td colspan="3">${esc(p.empresa.endereco||'-')}</td></tr></table><h2 class="pgr-sub">Atividades da organização</h2><div class="pgr-text">${esc(p.empresa.atividadeEmpresa||'-')}</div><h2 class="pgr-sub">Responsáveis técnicos cadastrados</h2><table class="pgr-table"><tr><th>SST</th><td>${esc(p.empresa.respSst||'-')} · ${esc(p.empresa.funcaoRespSst||'-')}</td></tr><tr><th>Médico do Trabalho</th><td>${esc(p.empresa.medicoTrabalho||'-')} ${p.empresa.crmMedico?' · '+esc(p.empresa.crmMedico):''}</td></tr><tr><th>Engenharia de Segurança</th><td>${esc(p.empresa.engSeguranca||'-')} ${p.empresa.creaEng?' · '+esc(p.empresa.creaEng):''}</td></tr></table>`,n++,total);
  html+=page(`<h1 class="pgr-title">2. Estrutura organizacional e grupos de exposição</h1><h2 class="pgr-sub">Setores</h2><table class="pgr-table"><thead><tr><th>Setor</th><th>Descrição</th><th>Ambiente</th></tr></thead><tbody>${(p.setores||[]).map(s=>`<tr><td>${esc(s.nome)}</td><td>${esc(s.descricao)}</td><td>${esc(s.ambiente)}</td></tr>`).join('')||'<tr><td colspan="3">Nenhum setor cadastrado.</td></tr>'}</tbody></table><h2 class="pgr-sub">Funções</h2><table class="pgr-table"><thead><tr><th>Função</th><th>Setor</th><th>Qtd.</th><th>Atividades</th></tr></thead><tbody>${(p.funcoes||[]).map(f=>`<tr><td>${esc(f.nome)}</td><td>${esc(f.setor)}</td><td>${esc(f.quantidade)}</td><td>${esc(f.atividades)}</td></tr>`).join('')||'<tr><td colspan="4">Nenhuma função cadastrada.</td></tr>'}</tbody></table><h2 class="pgr-sub">GHE</h2><table class="pgr-table"><thead><tr><th>GHE</th><th>Setor</th><th>Funções</th><th>Descrição</th></tr></thead><tbody>${(p.ghe||[]).map(g=>`<tr><td>${esc(g.nome)}</td><td>${esc(g.setor)}</td><td>${esc(g.funcoes)}</td><td>${esc(g.descricao)}</td></tr>`).join('')||'<tr><td colspan="4">Nenhum GHE cadastrado.</td></tr>'}</tbody></table>`,n++,total);
  html+=page(`<h1 class="pgr-title">3. Critérios de avaliação e classificação</h1><div class="pgr-text">Para priorização interna das ações preventivas, esta versão utiliza matriz 5 × 5 baseada na multiplicação entre Probabilidade (1 a 5) e Severidade (1 a 5). O resultado orienta a priorização e deve ser validado pela equipe responsável pelo GRO, considerando os critérios técnicos aplicáveis à organização.</div><h2 class="pgr-sub">Faixas internas</h2><div class="matrix"><div class="low">1–4<br>Baixo</div><div class="med">5–9<br>Moderado</div><div class="high">10–16<br>Alto</div><div class="crit">17–25<br>Crítico</div></div><h2 class="pgr-sub">Hierarquia de controles</h2><div class="pgr-text">As medidas propostas devem priorizar eliminação do perigo e redução dos riscos por medidas de prevenção, observando controles coletivos, administrativos/organizacionais e, quando cabível, equipamentos de proteção individual.</div>`,n++,total);
  riskChunks.forEach((ch,ix)=>{html+=page(`<h1 class="pgr-title">4. Inventário de riscos ${riskChunks.length>1?`(${ix+1}/${riskChunks.length})`:''}</h1><table class="pgr-table"><thead><tr><th>GHE / função</th><th>Grupo</th><th>Perigo / fator</th><th>Dano</th><th>P</th><th>S</th><th>Nível</th><th>Controles existentes</th></tr></thead><tbody>${ch.map(r=>`<tr><td>${esc(r.ghe||r.funcao||'-')}</td><td>${esc(r.grupo)}</td><td>${esc(r.perigo)}</td><td>${esc(r.dano)}</td><td>${esc(r.prob)}</td><td>${esc(r.sev)}</td><td>${level(Number(r.prob)*Number(r.sev))}</td><td>${esc(r.controles)}</td></tr>`).join('')||'<tr><td colspan="8">Nenhum risco cadastrado.</td></tr>'}</tbody></table>`,n++,total)});
  actionChunks.forEach((ch,ix)=>{html+=page(`<h1 class="pgr-title">5. Plano de ação ${actionChunks.length>1?`(${ix+1}/${actionChunks.length})`:''}</h1><table class="pgr-table"><thead><tr><th>Risco</th><th>Nível</th><th>Medida proposta</th><th>Responsável</th><th>Prazo</th><th>Status</th></tr></thead><tbody>${ch.map(r=>`<tr><td>${esc(r.perigo)}</td><td>${level(Number(r.prob)*Number(r.sev))}</td><td>${esc(r.acao)}</td><td>${esc(r.responsavel)}</td><td>${fmt(r.prazo)}</td><td>${esc(r.status||'Pendente')}</td></tr>`).join('')||'<tr><td colspan="6">Nenhuma ação cadastrada.</td></tr>'}</tbody></table>`,n++,total)});
  html+=page(`<h1 class="pgr-title">6. Conclusão e responsabilidades</h1><div class="pgr-text">Este documento consolida as informações cadastradas no sistema para o gerenciamento dos riscos ocupacionais da organização. O inventário de riscos e o plano de ação devem permanecer atualizados conforme mudanças nos processos, ambientes, atividades, controles e demais situações que alterem a exposição dos trabalhadores.</div><div class="sign-grid"><div class="sign">${esc(p.empresa.respSst||'Responsável SST')}<br>${esc(p.empresa.funcaoRespSst||'Segurança do Trabalho')}</div><div class="sign">${esc(p.empresa.responsavelEmpresa||'Responsável pela organização')}<br>Representante da organização</div></div>`,n++,total);
  return `<div class="pgr-doc">${html}</div>`
 }
 function print(p){let h=document.getElementById('printHost');if(!h){h=document.createElement('div');h.id='printHost';document.body.appendChild(h)}h.className='report-preview';h.innerHTML=build(p);const imgs=[...h.querySelectorAll('img')];let left=imgs.length;const go=()=>setTimeout(()=>window.print(),150);if(!left)return go();const done=()=>{left--;if(left<=0)go()};imgs.forEach(i=>i.complete?done():(i.onload=done,i.onerror=done));setTimeout(go,1800)}
 return{build,print,level,esc,fmt}
})();
